# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  python: circleci/python@2.1.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#

jobs:
  write-feature-flag-to-files:
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Call LaunchDarkly API
          command: |
              curl -H "Authorization: sdk-26799750-b3c4-4fff-a71d-037f25e49530" https://sdk.launchdarkly.com/sdk/latest-all | json_pp >flagdata.json
              git config --global push.autoSetupRemote true
              git config user.email "wanggloria21@gmail.com"
              git config user.name "CircleCI Job"
              git add .
              git commit --allow-empty -m "[ci skip] update flagdata.json based on LaunchDarkly call"
              git push 
  build:
    docker: 
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          # build the docker image based on the Dockerfile included in Repo.
          # then log in to docker hub & push this image
          command: |
            python3 main.py
            docker build -t ariv3ra/$IMAGE_NAME:$TAG . 
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push ariv3ra/$IMAGE_NAME:$TAG

  
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  call-launchdarkly-and-commit-flag-file:
    jobs:
        - write-feature-flag-to-files
        # - build:
        #     requires: 
        #         - write-feature-flag-to-files
